packages:
  - "packages/*"
  - "examples/ts/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
overrides:
  effect: 4.0.0-beta.88
  '@effect/vitest': 4.0.0-beta.88
minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.41.3'
