packages:
  - "packages/*"
  - "examples/ts/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
overrides:
  effect: 4.0.0-rc.115
  '@effect/vitest': 4.0.0-rc.115
  vitest: 5.0.1
minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.41.3'
